clone_folder: C:\VSTS

image: WMF 5

install:
  - cinst pester

version: 1.0.{build}

build_script:
- ps: .\Build\CreateModuleManifest.ps1

test_script:
- ps: .\Build\InvokeTests.ps1

deploy_script:
- ps: .\Build\PublishModule.ps1